# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Account(BaseModel):
    """
    Account
    """ # noqa: E501
    account_id: StrictStr
    entity_id: StrictStr
    account_type: StrictStr
    kyc_tier: StrictInt
    status: StrictStr
    opened_on: date
    risk_category: StrictStr
    declared_annual_income: Optional[Union[StrictFloat, StrictInt]] = None
    txn_count_7d: Optional[StrictInt] = 0
    txn_count_30d: Optional[StrictInt] = 0
    volume_7d: Optional[Union[StrictFloat, StrictInt]] = 0.0
    volume_30d: Optional[Union[StrictFloat, StrictInt]] = 0.0
    avg_monthly_volume: Optional[Union[StrictFloat, StrictInt]] = 0.0
    avg_monthly_count: Optional[Union[StrictFloat, StrictInt]] = 0.0
    unique_counterparties_30d: Optional[StrictInt] = 0
    last_active_ts: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["account_id", "entity_id", "account_type", "kyc_tier", "status", "opened_on", "risk_category", "declared_annual_income", "txn_count_7d", "txn_count_30d", "volume_7d", "volume_30d", "avg_monthly_volume", "avg_monthly_count", "unique_counterparties_30d", "last_active_ts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Account from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if declared_annual_income (nullable) is None
        # and model_fields_set contains the field
        if self.declared_annual_income is None and "declared_annual_income" in self.model_fields_set:
            _dict['declared_annual_income'] = None

        # set to None if last_active_ts (nullable) is None
        # and model_fields_set contains the field
        if self.last_active_ts is None and "last_active_ts" in self.model_fields_set:
            _dict['last_active_ts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Account from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_id": obj.get("account_id"),
            "entity_id": obj.get("entity_id"),
            "account_type": obj.get("account_type"),
            "kyc_tier": obj.get("kyc_tier"),
            "status": obj.get("status"),
            "opened_on": obj.get("opened_on"),
            "risk_category": obj.get("risk_category"),
            "declared_annual_income": obj.get("declared_annual_income"),
            "txn_count_7d": obj.get("txn_count_7d") if obj.get("txn_count_7d") is not None else 0,
            "txn_count_30d": obj.get("txn_count_30d") if obj.get("txn_count_30d") is not None else 0,
            "volume_7d": obj.get("volume_7d") if obj.get("volume_7d") is not None else 0.0,
            "volume_30d": obj.get("volume_30d") if obj.get("volume_30d") is not None else 0.0,
            "avg_monthly_volume": obj.get("avg_monthly_volume") if obj.get("avg_monthly_volume") is not None else 0.0,
            "avg_monthly_count": obj.get("avg_monthly_count") if obj.get("avg_monthly_count") is not None else 0.0,
            "unique_counterparties_30d": obj.get("unique_counterparties_30d") if obj.get("unique_counterparties_30d") is not None else 0,
            "last_active_ts": obj.get("last_active_ts")
        })
        return _obj


