# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.branches_api import BranchesApi


class TestBranchesApi(unittest.TestCase):
    """BranchesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BranchesApi()

    def tearDown(self) -> None:
        pass

    def test_create_branch_api_v1_branches_post(self) -> None:
        """Test case for create_branch_api_v1_branches_post

        Create Branch
        """
        pass

    def test_delete_branch_api_v1_branches_branch_id_delete(self) -> None:
        """Test case for delete_branch_api_v1_branches_branch_id_delete

        Delete Branch
        """
        pass

    def test_get_branches_api_v1_branches_get(self) -> None:
        """Test case for get_branches_api_v1_branches_get

        Get Branches
        """
        pass

    def test_update_branch_api_v1_branches_branch_id_patch(self) -> None:
        """Test case for update_branch_api_v1_branches_branch_id_patch

        Update Branch
        """
        pass


if __name__ == '__main__':
    unittest.main()
