# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.models.narrative_request import NarrativeRequest

class TestNarrativeRequest(unittest.TestCase):
    """NarrativeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NarrativeRequest:
        """Test NarrativeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NarrativeRequest`
        """
        model = NarrativeRequest()
        if include_optional:
            return NarrativeRequest(
                focused_pattern = '',
                all_patterns = [
                    null
                    ],
                shap_features = [
                    null
                    ]
            )
        else:
            return NarrativeRequest(
        )
        """

    def testNarrativeRequest(self):
        """Test NarrativeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
