# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataApi()

    def tearDown(self) -> None:
        pass

    def test_add_account_note_api_v1_accounts_account_id_notes_post(self) -> None:
        """Test case for add_account_note_api_v1_accounts_account_id_notes_post

        Add Account Note
        """
        pass

    def test_get_account_api_v1_accounts_account_id_get(self) -> None:
        """Test case for get_account_api_v1_accounts_account_id_get

        Get Account
        """
        pass

    def test_get_account_notes_api_v1_accounts_account_id_notes_get(self) -> None:
        """Test case for get_account_notes_api_v1_accounts_account_id_notes_get

        Get Account Notes
        """
        pass

    def test_get_all_accounts_api_v1_accounts_get(self) -> None:
        """Test case for get_all_accounts_api_v1_accounts_get

        Get All Accounts
        """
        pass

    def test_get_all_transactions_api_v1_transactions_get(self) -> None:
        """Test case for get_all_transactions_api_v1_transactions_get

        Get All Transactions
        """
        pass

    def test_get_transaction_api_v1_transactions_txn_id_get(self) -> None:
        """Test case for get_transaction_api_v1_transactions_txn_id_get

        Get Transaction
        """
        pass


if __name__ == '__main__':
    unittest.main()
