# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.fraud_api import FraudApi


class TestFraudApi(unittest.TestCase):
    """FraudApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FraudApi()

    def tearDown(self) -> None:
        pass

    def test_create_account_api_v1_accounts_post(self) -> None:
        """Test case for create_account_api_v1_accounts_post

        Create Account
        """
        pass

    def test_create_transaction_api_v1_transactions_post(self) -> None:
        """Test case for create_transaction_api_v1_transactions_post

        Create Transaction
        """
        pass

    def test_get_alert_details_api_v1_alerts_alert_id_get(self) -> None:
        """Test case for get_alert_details_api_v1_alerts_alert_id_get

        Get Alert Details
        """
        pass

    def test_get_alerts_quick_api_v1_alerts_quick_get(self) -> None:
        """Test case for get_alerts_quick_api_v1_alerts_quick_get

        Get Alerts Quick
        """
        pass

    def test_get_branch_channel_analytics_api_v1_analytics_branch_channel_get(self) -> None:
        """Test case for get_branch_channel_analytics_api_v1_analytics_branch_channel_get

        Get Branch Channel Analytics
        """
        pass

    def test_get_dormant_explanation_api_v1_explain_account_id_dormant_get(self) -> None:
        """Test case for get_dormant_explanation_api_v1_explain_account_id_dormant_get

        Get Dormant Explanation
        """
        pass

    def test_get_dormant_explanation_api_v1_explain_dormant_account_id_get(self) -> None:
        """Test case for get_dormant_explanation_api_v1_explain_dormant_account_id_get

        Get Dormant Explanation
        """
        pass

    def test_get_full_explanation_api_v1_explain_account_id_get(self) -> None:
        """Test case for get_full_explanation_api_v1_explain_account_id_get

        Get Full Explanation
        """
        pass

    def test_get_kyc_explanation_api_v1_explain_account_id_kyc_get(self) -> None:
        """Test case for get_kyc_explanation_api_v1_explain_account_id_kyc_get

        Get Kyc Explanation
        """
        pass

    def test_get_kyc_mismatch_explanation_api_v1_explain_kyc_mismatch_account_id_get(self) -> None:
        """Test case for get_kyc_mismatch_explanation_api_v1_explain_kyc_mismatch_account_id_get

        Get Kyc Mismatch Explanation
        """
        pass

    def test_get_live_feed_api_v1_feed_get(self) -> None:
        """Test case for get_live_feed_api_v1_feed_get

        Get Live Feed
        """
        pass

    def test_get_narrative_api_v1_narrative_account_id_post(self) -> None:
        """Test case for get_narrative_api_v1_narrative_account_id_post

        Get Narrative
        """
        pass

    def test_get_report_api_v1_report_account_id_get(self) -> None:
        """Test case for get_report_api_v1_report_account_id_get

        Get Report
        """
        pass

    def test_get_score_api_v1_score_account_id_get(self) -> None:
        """Test case for get_score_api_v1_score_account_id_get

        Get Score
        """
        pass

    def test_get_smurfing_explanation_api_v1_explain_account_id_smurfing_get(self) -> None:
        """Test case for get_smurfing_explanation_api_v1_explain_account_id_smurfing_get

        Get Smurfing Explanation
        """
        pass

    def test_get_smurfing_explanation_api_v1_explain_smurfing_account_id_get(self) -> None:
        """Test case for get_smurfing_explanation_api_v1_explain_smurfing_account_id_get

        Get Smurfing Explanation
        """
        pass

    def test_get_stats_api_v1_stats_get(self) -> None:
        """Test case for get_stats_api_v1_stats_get

        Get Stats
        """
        pass

    def test_get_trace_api_v1_trace_account_id_get(self) -> None:
        """Test case for get_trace_api_v1_trace_account_id_get

        Get Trace
        """
        pass

    def test_update_alert_status_api_v1_alerts_alert_id_status_patch(self) -> None:
        """Test case for update_alert_status_api_v1_alerts_alert_id_status_patch

        Update Alert Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
