# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.workflow_api import WorkflowApi


class TestWorkflowApi(unittest.TestCase):
    """WorkflowApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowApi()

    def tearDown(self) -> None:
        pass

    def test_approve_str_api_v1_alerts_alert_id_approve_str_post(self) -> None:
        """Test case for approve_str_api_v1_alerts_alert_id_approve_str_post

        Approve Str
        """
        pass

    def test_assign_alert_api_v1_alerts_alert_id_assign_post(self) -> None:
        """Test case for assign_alert_api_v1_alerts_alert_id_assign_post

        Assign Alert
        """
        pass

    def test_draft_str_api_v1_alerts_alert_id_draft_str_post(self) -> None:
        """Test case for draft_str_api_v1_alerts_alert_id_draft_str_post

        Draft Str
        """
        pass

    def test_get_audit_trail_api_v1_alerts_alert_id_audit_get(self) -> None:
        """Test case for get_audit_trail_api_v1_alerts_alert_id_audit_get

        Get Audit Trail
        """
        pass

    def test_reject_str_api_v1_alerts_alert_id_reject_str_post(self) -> None:
        """Test case for reject_str_api_v1_alerts_alert_id_reject_str_post

        Reject Str
        """
        pass


if __name__ == '__main__':
    unittest.main()
