# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.demo_api import DemoApi


class TestDemoApi(unittest.TestCase):
    """DemoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DemoApi()

    def tearDown(self) -> None:
        pass

    def test_cleanup_demo_api_v1_demo_cleanup_delete(self) -> None:
        """Test case for cleanup_demo_api_v1_demo_cleanup_delete

        Cleanup Demo
        """
        pass

    def test_inject_demo_api_v1_demo_inject_post(self) -> None:
        """Test case for inject_demo_api_v1_demo_inject_post

        Inject Demo
        """
        pass


if __name__ == '__main__':
    unittest.main()
