# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_config_stream_api_v1_stream_config_post(self) -> None:
        """Test case for config_stream_api_v1_stream_config_post

        Config Stream
        """
        pass

    def test_inject_fraud_api_v1_stream_inject_post(self) -> None:
        """Test case for inject_fraud_api_v1_stream_inject_post

        Inject Fraud
        """
        pass

    def test_read_root_get(self) -> None:
        """Test case for read_root_get

        Read Root
        """
        pass

    def test_reset_demo_data_api_v1_stream_reset_delete(self) -> None:
        """Test case for reset_demo_data_api_v1_stream_reset_delete

        Reset Demo Data
        """
        pass

    def test_start_stream_api_v1_stream_start_post(self) -> None:
        """Test case for start_stream_api_v1_stream_start_post

        Start Stream
        """
        pass

    def test_stop_stream_api_v1_stream_stop_post(self) -> None:
        """Test case for stop_stream_api_v1_stream_stop_post

        Stop Stream
        """
        pass

    def test_stream_status_api_v1_stream_status_get(self) -> None:
        """Test case for stream_status_api_v1_stream_status_get

        Stream Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
