# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.models.account import Account

class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Account:
        """Test Account
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Account`
        """
        model = Account()
        if include_optional:
            return Account(
                account_id = '',
                entity_id = '',
                account_type = '',
                kyc_tier = 56,
                status = '',
                opened_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                risk_category = '',
                declared_annual_income = 1.337,
                txn_count_7d = 56,
                txn_count_30d = 56,
                volume_7d = 1.337,
                volume_30d = 1.337,
                avg_monthly_volume = 1.337,
                avg_monthly_count = 1.337,
                unique_counterparties_30d = 56,
                last_active_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Account(
                account_id = '',
                entity_id = '',
                account_type = '',
                kyc_tier = 56,
                status = '',
                opened_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                risk_category = '',
        )
        """

    def testAccount(self):
        """Test Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
