# coding: utf-8

"""
    G-TEN  

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gten_internal.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_api_v1_auth_users_post(self) -> None:
        """Test case for create_user_api_v1_auth_users_post

        Create User
        """
        pass

    def test_delete_user_api_v1_auth_users_user_id_delete(self) -> None:
        """Test case for delete_user_api_v1_auth_users_user_id_delete

        Delete User
        """
        pass

    def test_generate2fa_api_v1_auth2fa_generate_post(self) -> None:
        """Test case for generate2fa_api_v1_auth2fa_generate_post

        Generate 2Fa
        """
        pass

    def test_get_investigators_api_v1_auth_users_investigators_get(self) -> None:
        """Test case for get_investigators_api_v1_auth_users_investigators_get

        Get Investigators
        """
        pass

    def test_login_for_access_token_api_v1_auth_login_post(self) -> None:
        """Test case for login_for_access_token_api_v1_auth_login_post

        Login For Access Token
        """
        pass

    def test_read_users_me_api_v1_auth_me_get(self) -> None:
        """Test case for read_users_me_api_v1_auth_me_get

        Read Users Me
        """
        pass

    def test_update_user_password_api_v1_auth_users_user_id_password_patch(self) -> None:
        """Test case for update_user_password_api_v1_auth_users_user_id_password_patch

        Update User Password
        """
        pass

    def test_verify2fa_api_v1_auth2fa_verify_post(self) -> None:
        """Test case for verify2fa_api_v1_auth2fa_verify_post

        Verify 2Fa
        """
        pass


if __name__ == '__main__':
    unittest.main()
