events { worker_connections 1024; }
http {
    upstream tracex_api_backend {
        # Primary Cloud Data Center (Mumbai - ap-south-1a)
        server api-mumbai:8000 max_fails=1 fail_timeout=2s;

        # Disaster Recovery Standby Node (Hyderabad - ap-south-1b)
        server api-hyderabad:8000 backup;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://tracex_api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass_header X-Data-Center;
            proxy_connect_timeout 1s;
        }
    }
}
